### DISCUSSION TITLE
Parallel execution with matrix of containers?

### DISCUSSION THREAD

**Discussion by pthexton** [cirruslabs/cirrus-cli#563] [General]
Firstly, thanks for the work you guys have done on cirrus-cli and cirrus-tart !

Is it possible to be able leverage macOS's support for running 2 macOS VMs in parallel?  For example, if I have a task I want to run on both macOS Monterey and macOS Ventura (currently beta), I can configure it as

```
task:
  name: Automation
  matrix:
    macos_instance:
      image: ventura
    macos_instance:
      image: monterey
...
```

This works, but doing a `cirrus run` performs the task on each OS one after the other.  Presumably this may be awkward as the engine would need to know it can only run 2 at a time (should somebody configure, say, 4 different containers in the matrix section), but I was just wondering if this can already be done and I've just missed it in the documentation.
