### DISCUSSION TITLE
[Question] Can I run the task with macos_instance VMs but run on the github runner ubuntu-latest?

### DISCUSSION THREAD

**Discussion by littleGnAl** [cirruslabs/cirrus-cli#599] [Q&A] [answered]
Say that I have a GitHub action file `.github/workflows/cirrus.yml` like:
```yaml
name: Run Cirrus Tasks

on: [push, pull_request]

jobs:
  cirrus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cirruslabs/cirrus-action@master
```
And a `.cirrus.yml` like:
```yaml
macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

task:
  script: echo "Hello World from macOS!"
```

When the action run, is the `script: echo "Hello World from macOS!"` actually run on `ubuntu-latest` or `ghcr.io/cirruslabs/macos-ventura-base:latest`?
