### ISSUE TITLE
Respect CIRRUS_WORKING_DIR in dirty mode

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#163]
`--dirty` should mount project dir into the specified `CIRRUS_WORKING_DIR`. Here is `.cirrus.yml` example which should pass:

```yaml
task:
  container:
    image: alpine:latest
  env:
    CIRRUS_WORKING_DIR: /defs
  test_script: test -f .cirrus.yml
```
