### ISSUE TITLE
Support isolation via Parallels VMs in persistent worker mode

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#198]
Right now persistent worker mode simple shells out the task without any isolation. Will be great to have an option to specify isolation using Parallels Desktop Pro. For example,

```yaml
mac_m1_task:
  persistent_worker:
    isolation:
      parallels:
        vm_name: big-sur-base
        platform: darwin
        user: admin # for SSHing to start a task
        password: admin # same ^^
    labels:
      os: darwin
      arch: arm64
```
