### ISSUE TITLE
Required groups should be stable

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#199]
Right now it seems local index and therefore required groups are set after the `only_if` filtration. To comply with the cloud parser the local group id should be stable regardless if tasks in between are filtered out.

**Comment by edigaryev** [comment]
Could you provide a more specific example? Because the example that I've came up with passes the RPC tests just fine:

```yaml
container:
  image: debian:latest

task:
  only_if: true == false
  script: uptime

task:
  script: date
```

...with the last task having `local_group_id == 1` and `indexWithinBuild == 0`.

**Comment by fkorotkov** [comment]
Don't recall the exact config but probably something like:

```yaml
container:
  image: debian:latest

list_task:
  only_if: false
  script: uptime

test_task:
  script: uptime

deploy_task:
  depends_on:
    - lint
    - test
  script: date
```
