### ISSUE TITLE
Log rotations for Persistent Workers

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#236]
It will be great to provide an easy builtin functionality for log ration for persistent worker mode. For example, https://github.com/natefinch/lumberjack can be used and configured in the persistent worker configuration file:

```yaml
name: worker 1
token: ....

logs:
  filename: /tmp/cirrus-worker.log
  maxAge: 180
```
