### ISSUE TITLE
Validate dependecy names

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#355]
Validate that all task names in `depends_on` are from existing tasks:

```yaml
container:
  image: latest

foo_task:
  script: echo foo

bar_task:
  depends_on: fooo
  script: echo bar
```
