### ISSUE TITLE
Support Docker isolation for persistent worker mode

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#374]
Right now only None or Parallels isolations are supported. In some rare cases it seems it's reasonable to support Docker isolation as well. I know it's possible to just use `container`s for that reason but here is a use case:

Building Android Open Source Project requires a huge `ccache`. It's a waste to always archive and unarchive `ccache`. But is a persistent worker could have a Docker isolation with an option to mount a local `ccache` folder then it should all work perfectly. See:

```yaml
persistent_worker:
  isolation:
    docker:
      image: ubuntu:latest
      cpu: 24
      memory: 60G
      mount:
        - /root/.ccache:/root/.ccache
```
