### ISSUE TITLE
Add a warning when task name is overriden

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#427]
Add a warning to the parser that a name is overriden in such cases:

```yaml
rspec_code_task:
  matrix:
    name: Code (shard 1)
    name: Code (shard 2)
    name: Code (shard 3)
```

Such config might confuse people on what to use in `depends_on`.
