### ISSUE TITLE
Support running macos_instance via tart

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#502]
Let's support running `macos_instance` via tart the same way we have `container`s running via Docker/Podman.

```yaml
macos_instance:
  image: ghcr.io/cirruslabs/macos/monterey-vanilla:12.3.1
  user: custom-user # default is admin 
  password: custom-password # default is admin

task:
  script: echo "Hello from Tart VM!"
```
