### ISSUE TITLE
Support resource management for persistent worker mode

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#504]
Let's start supporting running multiple tasks in parallel for a given worker. I propose to add a mapping to the config file with the available resources. For example:

```yaml
labels:
  tart: installed

resources:
  macos-vms: 2.0
```

Then we can modify `WorkerInfo` message that we pass in `PollRequest` to include `available_resources`:

```protobuf
message WorkerInfo {
  map<string, string> labels = 1;
  map<string, double> available_resources = 2;
}
```

And respectively `PollResponse`'s `AgentAwareTask` will include new `resources` field.

Here is an example of how it will work:

1. Worker will initially poll with the `available_resources` equal to the one in the config.
2. Once `PollResponse` is returned. Will subtract `AgentAwareTask`'s `resources` from the `available_resources` for future polls.
  -  If `AgentAwareTask`'s `resources` are empty let's assume the tasks consumes all of the available resources.
3. Worker will start executing the task and will include the updated `available_resources` in the new polls.
4. Once task finishes the worker should add the resources back to `available_resources`.

On the cloud side we'll modify the `persisten_worker` side to include the resources along the labels:

```yaml
task:
  persistent_worker:
    labels:
      os: darwin
      arch: arm64
      tart: installed
    resources:
      macos-vm: 1
    isolation:
      tart:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
  script: echo "running on-premise in a VM"
```
