### ISSUE TITLE
Improve testing of resulting tasks graph

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#521]
Right now `cirrus internal run` checks if the resulting generated YAML is the same as `.cirrus.expected.yml`. Note that `.cirrus.expected.yml` is equal to the original `.cirrus.yml` if any plus appended output of execution of `.cirrus.star`.

What if we will go a bit further and allow to check the resulting graph of tasks after all the `only_if`s, `skip`s and others are applied. Let's call it `.cirrus.expected.graph.yml` with a simplified format where a `task` only have a `name`, `status` (can be `SKIPPED`), `depends_on` (with filtered out tasks after `only_if`).

```yaml
# .cirrus.expected.graph.yml
task:
  name: Build
  status: CREATED
  local_group_id: 0

task:
  name: Validate
  status: CREATED
  local_group_id: 1
  required_groups:
    - 0
```

This way people with very complex existing YAML pipelines can start testing them and checking that the output graph of tasks for different environments is as they expect.
