### ISSUE TITLE
Can cirrus-cli be run locally to preserve an artifact built in a tart image (without using cirrus cloud CI)?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [cirruslabs/cirrus-cli#526]
The cirrus-cli tool looks amazing, this is going to be hugely useful. I have a tart image available locally and this configuration file:

```
task:
  name: Build Python wheel
  macos_instance:
    image: monterey-base-ci
  build_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python3 -m pip install pip wheel setuptools
    - cd toml
    - python3 setup.py bdist_wheel
  binaries_artifacts:
    path: toml/dist/*.whl
```

After completing running `cirrus run -o simple`, it says:

```
'build' script succeeded in 3.3s!
Started 'binaries' artifacts
Uploading 1 artifacts for /tmp/cirrus-ci/working-dir/toml/dist/*.whl
Uploaded /tmp/cirrus-ci/working-dir/toml/dist/toml-0.10.2-py2.py3-none-any.whl
'binaries' artifacts succeeded in 0.0s!
'Build Python wheel' Task succeeded in 13s!
```

I am struggling to find out where the binary file go? I.e. how do I get it on the machine where I ran the `cirrus run` command. The [docs](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) are focused on CI use case. Is this at all supported to be run locally?
