### ISSUE TITLE
Allow credentials to be specified unencrypted

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#535]
Once https://github.com/cirruslabs/cirrus-ci-docs/issues/979 is added let's allow to specify `gcp_credentials` like this:

```yaml
gcp_credentials:
  workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
```

This should result in credentials being populated with a JSON representation of the child node. For the example it will be:

```json
{
  "workload_identity_provider": "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider",
  "service_account": "my-service-account@my-project.iam.gserviceaccount.com"
}
```
