### ISSUE TITLE
Local run does nothing?

### ISSUE THREAD

**Issue by AstraLuma** [cirruslabs/cirrus-cli#574]
With a trivial cirrus file

```
example_task:
  container:
    image: debian
  bar_step:
    - echo bar
```

Running `cirrus run` does nothing:

```
$ ~/Downloads/cirrus-linux-amd64 run
$ ~/Downloads/cirrus-linux-amd64 --version
cirrus version 0.88.0-b1743e6
```

I've tried scrubbing both docker and `~/.cache/cirrus` and I'm not sure what's causing this behavior.
