### ISSUE TITLE
Use a dynamic image in cirrus.yaml

### ISSUE THREAD

**Issue by mitissen** [cirruslabs/cirrus-cli#601]
Hi,

i'am using cirrus-cli with tart. 
Is there a possibility to dynamicly set the image?

```yaml
task:
  name: build
  macos_instance:
    image: imageName <--
  build_script:
    ...
```
As far as I have tested you can not pass the image as a variable.

If you have no possibility to change the image dynamically e.g. by environment variables.

Wouldn't it be a good feature to pass the image as a parameter of cirrus-cli?

`cirrus run --image imageToUseForThisRun`

**Comment by fkorotkov** [comment]
You can use environment variables for it:

```
task:
  name: build
  macos_instance:
    image: $TART_IMAGE
  build_script:
    # ...
```

```shell
cirrus run --environment TART_IMAGE=imageToUseForThisRun
```
