### ISSUE TITLE
Error starting command with any configuration.

### ISSUE THREAD

**Issue by stanogn** [cirruslabs/cirrus-cli#620]
`Error starting command: fork/exec /bin/bash: no such file or directory`

I am getting this error no matter which task definition i try. I also tried some of the examples and it seems it cant run any commands.
I also tried googling with no results.

I am running this on macos 13.3.1 and the VM image is macos 12.6

**Comment by edigaryev** [comment]
I am afraid that we'll still need your task definition to diagnose the issue.

I'm assuming that you're using `macos_instance`. Have you tried running  against `ghcr.io/cirruslabs/macos-ventura-base:latest` (or `ghcr.io/cirruslabs/macos-monterey-base:latest`) VM images?

Which Cirrus CLI version are you using (`cirrus --version`)?

**Comment by stanogn** [comment]
> ghcr.io/cirruslabs/macos-monterey-base:latest

Thanks for the quick response!
I tried this config and still got the same result:
```
macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  name: test-task
  build_script: echo hello
```

**Comment by edigaryev** [comment]
I've just ran your configuration and it worked just fine:

```
% cat .cirrus.yml 
macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  name: test-task
  build_script: echo hello
```

```
% cirrus run     
✅ 'test-task' task 13s
% cirrus --version
cirrus version 0.98.0-21e0ceb
```

The `Error starting command` is coming [from the `cirrus-ci-agent`](https://github.com/cirruslabs/cirrus-ci-agent/blob/6093bc7d29d70960aca57f9852a541b2e4c8ff4d/internal/executor/shell.go#L180) which Cirrus CLI puts inside of a VM and runs over SSH.

`/bin/bash` exists in both VM images that I've mentioned above and is only selected by the agent if it exists in `PATH` on the target system (in your case it's VM).

So overall, it looks like this should not be happening.
