### ISSUE TITLE
cirrus run should allow to filter by labels

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#63]
Related to #62. When there are bunch of tasks with the same name but different labels (container image, some env variables) it not possible to target a particular task. `cirrus run` should be able to match by `UniqueName` too.

**Comment by edigaryev** [comment]
Can you provide a few example `cirrus run` invocations that demonstrate the filtering by labels?

I'm wondering how this will actually work with multiple tags (labels)? Perhaps we need to implement some basic wildcard matching after all?

**Comment by fkorotkov** [comment]
I imagine something like `cirrus run "test VERSION:1.15"` for 

```yaml
test_task:
  env:
    matrix:
      VERSION: 1.15
      VERSION: 1.14
  container:
    image: golang:$VERSION
```
