### ISSUE TITLE
Not detected INVALID_ARGUMENT task has background script and artifacts instructions with an identical name

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [cirruslabs/cirrus-cli#633]
```yaml
a_task:
  recording_background_script: >
    ...
  always:
    recording_artifacts:
      path: ...
```
raises on execution:
```
Error while parsing tasks: INVALID_ARGUMENT: parsing error: task 'a_task' has background script and artifacts instructions with an identical name 'recording'!
```
but this is not reported by `cirrus validate`

cirrus version 0.101.1-63e767b
