### ISSUE TITLE
Tart: allow configuring volumes

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#640]
Since Tart can mount volumes we should expose it in the isolation support (note it should also be configured like #639 for security reasons).

Also since for isolation we know username/password we can do something fancy and ssh into the VM and mount the virtiofs (or just symlink) where specified by user:

```yaml
task:
  persistent_worker:
    isolation:
      tart:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
        volumes:
          - source: /tmp/cirrus-workdir-$CIRRUS_TASK_ID
             target: /Users/admin/workdir
             cleanup_source: true
```

Additionally we can support specifying a remote archive as a `source`. This way we can always have the latest GitHub Actions runners inside the VM for our Cirrus Runners.

TBD if providing a URL should be supported by the CLI or Tart itself. Might be useful to have it in Tart for other folks and since we have cache with cleanup mechanism already builtin.
