### ISSUE TITLE
Syncing working directory - endless loop

### ISSUE THREAD

**Issue by findthebug** [cirruslabs/cirrus-cli#644]
Default cirrus script with Tart Image. Run Tart VM without cirrus, VM starts all good. If i use cirrus to start VM, i got message  syncing working directory which blocks VM to start.

```
task:
  name: xCode Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  task_script:
    - echo "Hello from within a Tart VM!"
```

```
🕙 'xCode Build' task 03:39
   ✅ pull virtual machine 0.5s
   ✅ clone virtual machine 0.1s
   ✅ boot virtual machine 6.3s
   🕙 syncing working directory 03:27
```
