### ISSUE TITLE
task timed out: no heartbeats were received in the last 2m0s

### ISSUE THREAD

**Issue by inkeliz** [cirruslabs/cirrus-cli#656]
I'm not sure if that is a cirrus-cli issue or docker, I'm using the following YML:

```
efficient_task:
  container:
    dockerfile: .cirrus-ci/Dockerfile
  test_script:
    zig test src 
```
Running `cirrus run` results:

```
[Logs]
task timed out: no heartbeats were received in the last 2m0s
```

```
Error: build failed: task Prebuild .cirrus-ci/Dockerfile (1) timed out
2023/10/04 15:54:09 build failed: task Prebuild .cirrus-ci/Dockerfile (1) timed out
```

EDIT: It always happens with 2minutes, have any way to remove that limit?
