### ISSUE TITLE
Better shell completion

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-cli#712]
Assumptions:
- I am using a modern Zsh (v5) with shell completions enabled
- My `.cirrus.yaml` has the following tasks:

  ```yaml
  deploy_android_app_task:
    # ...
  deploy_ios_app_task:
    # ...
  ```

### Current behavior

When completion is triggered, contents of `$PWD` are listed. This is default behavior and not useful.

```
$ cirrus run [tab]
<files in $PWD are printed>
```

### Expected behavior

Completions are shown:

```
$ cirrus run [tab]
deploy_android_app    deploy_ios_app
```

### Expected behavior (even better)

Let's assume the following `.cirrus.yaml`:

```yaml
deploy_android_app_task:
  name: Deploy Android app to Google Play
  # ...
deploy_ios_app_task:
  name: Deploy iOS app to App Store
  # ...
```

Task IDs are shown and task name is the description:

```
$ cirrus run [tab]
deploy_android_app  -- Deploy Android app to Google Play
deploy_ios_app      -- Deploy iOS app to App Store
```

However it seems like this would require more changes, because currently Cirrus CLI ignores `deploy_android_app_task` when `name: Deploy Android app to Google Play` is present. See #713.

### Implementation

Since Cirrus CLI uses [Cobra](https://github.com/spf13/cobra), which has [excellent support for shell completons](https://github.com/spf13/cobra/blob/v1.8.0/site/content/completions/_index.md) and supports the use case described above.

I'm happy to submit a PR for this when I find some free time.
