### ISSUE TITLE
Task dependency is not respected when running locally

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-cli#761]
### Reproduction

**.cirrus.yaml**
```yaml
task:
  name: build
  container:
    image: alpine:3.20
  script: |
    echo "Hello from build task on $(uname -a)"

task:
  name: test
  container:
    image: alpine:3.19
  depends_on:
    - build
  script: |
    echo "Hello from test task on $(uname -a)"
```

**Run**

```console
cirrus run --output simple test
```

### Expected

both scripts are executed

### Actual

only the latter script is executed
