### ISSUE TITLE
Can Docker Pipe be used with custom Dockerfile?

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-cli#770]
For example:

```yaml
pipe:
  name: Build and validate
  steps:
    - image: .cirrus/Dockerfile
      build_script: gradlew :maestro-cli:installDist
    - image: eclipse-temurin:8-jre-alpine
      validate_script: ./maestro-cli/build/outputs/install/maestro --version
```

**.cirrus/Dockerfile**

```Dockerfile
FROM ghcr.io/cirruslabs/android-sdk:34

RUN apt-get update && apt-get install -y \
    nodejs \
    && rm -rf /var/lib/apt/lists/*
```
